spring:
  datasource:
    # 一般写法
    #driver-class-name: com.mysql.cj.jdbc.Driver
    # 插件五：使用插件执行 SQL 分析打印，生产环境不要使用
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    # 一般url写法
    #url: jdbc:mysql://192.168.1.8:3306/db_mybatisplus?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    # 插件五：使用插件执行 SQL 分析打印，生产环境不要使用
    url: jdbc:p6spy:mysql://192.168.1.8:3306/db_mybatisplus?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8

    username: root
    password: ;Flzxsqc1
logging:
  level:
    root: warn
    com.liuhang.mybatisplus.mybatisplusday01advanced.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:

  global-config:
    db-config:
      # 插件一：逻辑删除：0表示逻辑上未删除，比如：在职的员工
      logic-not-delete-value: 0
      # 插件一：逻辑删除：1表示逻辑上已删除，比如：已经离职的员工
      logic-delete-value: 1
